Repository prgrms-fe-devcourse/FEDC4_Angola_NaYoung, pull requests merged in 2023-09, with the labels that each got.

#15 [API] - Auth api 함수 작성
  src/apis/auth.ts
  src/apis/instance.ts
  src/atoms/index.ts
  src/components/FetchTest/index.tsx
  src/storage/index.ts
  src/types/auth.ts
Labels: 세진

#16 [API] - Post api 함수 작성
  src/apis/index.ts
  src/apis/post.ts
Labels: 주하

#19 [API] - Comment, Notification API hook 구현
  src/apis/comment.ts
  src/apis/notifications.ts
Labels: 민우

#20 [API] - Follow Like Search api 함수 작성
  src/apis/follow.ts
  src/apis/like.ts
  src/apis/search.ts
Labels: 영준

#28 [Component] - Header 컴포넌트 구현
  src/components/Header/constants/index.ts
  src/components/Header/index.tsx
  src/components/Header/utils/index.ts
  src/utils/index.ts
Labels: 영준

#26 [Component] - Button 컴포넌트 구현
  src/components/Button/index.tsx
Labels: 주하

#30 [Component] - SearchBar 컴포넌트 구현
  src/components/SearchBar/index.tsx
Labels: 민우

#31 [Component] - NavBar 컴포넌트 구현
  src/components/Navbar/LinkButton.tsx
  src/components/Navbar/Menubar/AuthMenubar.tsx
  src/components/Navbar/Menubar/CommonMenubar.tsx
  src/components/Navbar/Menubar/NonAuthMenubar.tsx
  src/components/Navbar/Menubar/index.ts
  src/components/Navbar/index.tsx
Labels: 지윤

#35 [Spinner] - Spinner 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Spinner/index.tsx
  src/components/index.ts
Labels: 민우

#36 [Component] - Main 컴포넌트 구현
  src/components/Main/index.tsx
  src/hooks/useCurrentPage.ts
  src/routes/index.ts
  src/utils/parseQueryString.ts
  tsconfig.json
  vite.config.ts
Labels: 세진

#39 [Page] - Login 페이지 구현
  src/App.tsx
  src/apis/post.ts
  src/pages/LogIn/index.tsx
Labels: 주하

#42 [Page] - 검색 페이지 구현
  src/apis/search.ts
  src/components/PostList/index.tsx
  src/components/PostList/utils/index.ts
  src/components/PostListItem/index.tsx
  src/components/UserList/index.tsx
  src/components/UserList/utils/index.ts
  src/components/UserListItem/index.tsx
  src/pages/SearchPage/index.tsx
Labels: 영준

#41 [Page] - SignUp 페이지 구현
  src/apis/auth.ts
  src/apis/post.ts
  src/apis/user.ts
  src/pages/LogIn/index.tsx
  src/pages/SignUp/SignUpModals.tsx
  src/pages/SignUp/index.tsx
Labels: 주하

#48 [Fix] - user api 수정
  src/apis/user.ts
Labels: 지윤

#50 [Util] - 문자열 데이터 split, join 함수 구현
  src/hooks/useCurrentPage.ts
  src/utils/index.ts
  src/utils/parseDataBySeparator.ts
  src/utils/parseQueryString.ts
Labels: 세진

#53 [Component] - Main 컴포넌트에서 route 데이터 수정
  src/hooks/useCurrentPage.ts
  src/routes/index.ts
Labels: 세진

#56 [Component] - Post 컴포넌트 중간 merge
  src/apis/post.ts
  src/components/Post/index.tsx
  src/components/PostListItem/index.tsx
  src/pages/tempPages.tsx
Labels: 세진

#57 [Component] - Post > PostViewer 이름 수정
  src/components/PostViewer/index.tsx
  src/pages/tempPages.tsx
Labels: 세진

#54 [Page] - UserPage 구현
  src/apis/user.ts
  src/components/PostListItem/index.tsx
  src/components/UserListItem/index.tsx
  src/main.tsx
  src/pages/UserPage/UserInfo.tsx
  src/pages/UserPage/index.tsx
  src/styles/index.ts
  src/styles/resetStyles.ts
Labels: 지윤

#58 [Page] - MyPage 구현
  src/apis/profile.ts
  src/apis/user.ts
  src/components/UserListItem/index.tsx
  src/pages/MyPage/MyInfo.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/utils/index.ts
  src/pages/UserPage/UserInfo.tsx
Labels: 지윤

#59 [Page] - CreatePost 페이지 구현
  src/apis/post.ts
  src/pages/CreatePostPage/CreatePostSuccessModal/index.tsx
  src/pages/CreatePostPage/index.tsx
  src/pages/index.ts
Labels: 민우

#60 [Page] - Home 페이지 구현
  src/apis/post.ts
  src/components/PostList/utils/index.ts
  src/pages/HomePage/index.tsx
  src/pages/index.ts
  src/pages/tempPages.tsx
Labels: 영준

#64 [Style] - NavBar, Main 컴포넌트 CSS 스타일링 구현
  src/App.tsx
  src/components/Header/index.tsx
  src/components/LinkButton/index.tsx
  src/components/Main/index.tsx
  src/components/NavBar/MenuBar/AuthMenuBar.tsx
  src/components/NavBar/MenuBar/CommonMenuBar.tsx
  src/components/NavBar/MenuBar/NonAuthMenuBar.tsx
  src/components/NavBar/index.tsx
  src/components/PostListItem/index.tsx
  src/components/UserListItem/index.tsx
  src/pages/CreatePostPage/CreatePostSuccessModal/index.tsx
  src/styles/icons/SearchIcon.tsx
  src/styles/resetStyles.ts
Labels: 민우

#65 [Component] - Post 컴포넌트
  package-lock.json
  package.json
  src/components/Modal/index.tsx
  src/components/PostList/index.tsx
  src/components/PostListItem/index.tsx
  src/components/PostViewer/ButtonGroup.tsx
  src/components/PostViewer/NonAuthModal.tsx
  src/components/PostViewer/PostContents.tsx
  src/components/PostViewer/PostTitle.tsx
  src/components/PostViewer/index.tsx
  src/pages/tempPages.tsx
  src/styles/contants.ts
  src/utils/getRandomTwoColor.ts
  src/utils/index.ts
Labels: 세진

#67 [Page] - MyPage 프로필 변경, 유저 레벨 계산 유틸 함수
  src/apis/profile.ts
  src/components/UserListItem/index.tsx
  src/pages/MyPage/MyInfo.tsx
  src/pages/UserPage/UserInfo.tsx
  src/utils/calculateUserLevel.ts
Labels: 지윤

#69 Feat/#62/mypage profile image
  src/components/PostListItem/index.tsx
  src/components/UserList/index.tsx
  src/components/UserListItem/index.tsx
  src/pages/MyPage/MyInfo.tsx
  src/pages/MyPage/index.tsx
  src/pages/UserPage/UserInfo.tsx
  src/pages/UserPage/index.tsx
Labels: 지윤

#72 [Fix] - 정렬 수정
  src/components/Header/index.tsx
  src/components/Main/index.tsx
  src/components/PostList/index.tsx
  src/components/PostList/utils/index.ts
  src/components/UserList/index.tsx
  src/components/UserList/utils/index.ts
  src/components/UserListItem/index.tsx
Labels: 영준

#78 [Notification] - PostPage에서 댓글 알림 생성 기능 구현
  src/pages/PostPage/index.tsx
Labels: 주하

#82 [Style+Component] - 스타일 객체 추가, NameTag 컴포넌트 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/Icon/index.tsx
  src/components/NameTag/index.tsx
  src/components/PostViewer/PostTitle.tsx
  src/components/PostViewer/index.tsx
  src/components/UserList/index.tsx
  src/components/UserList/utils/index.ts
  src/main.tsx
  src/pages/HomePage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/PostPage/index.tsx
  src/pages/UserPage/index.tsx
  src/styles/commonStyles.ts
  src/styles/contants.ts
  src/utils/calculateUserLevel.ts
  src/utils/getRandomTwoColor.ts
  src/utils/index.ts
Labels: 세진

#85 [Util] - pxToRem 함수 구현
  src/utils/index.ts
  src/utils/pxToRem.ts
Labels: 주하

#83 [Component] - Button 컴포넌트 UI 수정
  src/components/Button/index.tsx
Labels: 주하

#89 [Style] - 수정/ANGOLA_STYLES.textSize.titleLg
  src/styles/commonStyles.ts
Labels: 세진

#92 [Style] - 수정/commonStyles.css 추가
  src/main.tsx
  src/styles/commonStyles.css
  src/styles/commonStyles.ts
  src/styles/resetStyles.ts
Labels: 세진

#98 [Style] - resetCSS, commonCSS 겹침으로 인한 스타일 적용 안되는 문제 해결
  src/App.tsx
  src/styles/commonStyles.css
Labels: 민우

#90 [Feat] - MyPage에서 Post 삭제 기능 추가
  src/apis/post.ts
  src/components/Modal/index.tsx
  src/components/PostListItem/index.tsx
  src/pages/MyPage/index.tsx
Labels: 지윤

#95 [Notification] - PostViewe 좋아요 알림 생성 기능 구현
  src/components/PostViewer/ButtonGroup.tsx
  src/components/PostViewer/index.tsx
Labels: 세진

#101 [Style] - Header 컴포넌트 style 추가
  src/components/Header/index.tsx
  src/components/Icon/index.tsx
Labels: 영준

#107 [Style] - 검색 페이지 style 추가
  src/components/Image/index.tsx
  src/components/PostList/index.tsx
  src/components/PostListItem/index.tsx
  src/components/UserList/index.tsx
  src/components/UserListItem/index.tsx
  src/pages/SearchPage/index.tsx
Labels: 영준

#110 [Refactor] - Header 컴포넌트 리팩토링 작업
  src/components/Header/Hooks/useSort.ts
  src/components/Header/TabBarList/index.tsx
  src/components/Header/constants/index.ts
  src/components/Header/index.tsx
  src/components/Header/utils/index.ts
Labels: 영준

#109 [Style] - SignUpPage, LoginPage UI 스타일링 추가
  public/images/LOGO_FULL.svg
  src/components/Button/index.tsx
  src/components/Icon/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/SignUpPage/Modals.tsx
  src/pages/SignUpPage/SignUpModals.tsx
  src/pages/SignUpPage/index.tsx
  src/utils/index.ts
  src/utils/userAuthentication.ts
Labels: 주하

#111 [Create-post] - 포스트 작성 페이지 모달 수정 및 style 구현
  src/components/SearchBar/index.tsx
  src/pages/CreatePostPage/CreatePostSuccessModal/index.tsx
  src/pages/CreatePostPage/index.tsx
  src/styles/commonStyles.ts
Labels: 민우

#112 [Style] - PostViewer 스타일 추가
  src/components/Icon/index.tsx
  src/components/NameTag/index.tsx
  src/components/PostViewer/ButtonGroup.tsx
  src/components/PostViewer/PostContents.tsx
  src/components/PostViewer/PostTitle.tsx
  src/components/PostViewer/index.tsx
  src/pages/PostPage/index.tsx
  src/styles/commonStyles.ts
Labels: 세진

#113 [Component] - modal 닫힘 오류 수정
  src/components/Modal/index.tsx
Labels: 세진

#114 [Style] - PostPage UI 스타일링 구현
  src/components/Button/index.tsx
  src/pages/PostPage/CommentList.tsx
  src/pages/PostPage/MakeComment.tsx
  src/pages/PostPage/Turnout.tsx
  src/pages/PostPage/index.tsx
Labels: 주하

#104 [Refactor & Style] UserPage 리팩토링 및 UI 작업
  public/images/default.png
  public/images/temp.png
  src/components/Button/index.tsx
  src/constants/index.ts
  src/pages/UserPage/UserInfo.tsx
  src/pages/UserPage/constants/index.ts
  src/pages/UserPage/hooks/useFollow.ts
  src/pages/UserPage/index.tsx
Labels: 지윤

#117 [Style] - Home 페이지 style 추가
  src/pages/HomePage/index.tsx
Labels: 영준

#120 [Refactor] - Header 컴포넌트 리팩토링 작업
  src/components/Header/Hooks/useSelect.ts
  src/components/Header/index.tsx
Labels: 영준

#122 [Fix] - Main 컴포넌트 검색어 수정
  src/components/Main/index.tsx
Labels: 영준

#124 [Refactor] - Header 컴포넌트 테두리 수정
  src/components/Header/index.tsx
Labels: 영준

#129 [Fix+Public] - loginPage svg 오류 수정, 404 캐릭터 이미지 추가
  public/images/angola_404.svg
  src/pages/LoginPage/index.tsx
Labels: 세진

#125 [Refactor] - Post Viewer 리팩터링
  src/components/Header/index.tsx
  src/components/Icon/index.tsx
  src/components/PostViewer/ButtonGroup.tsx
  src/components/PostViewer/components/ButtonGroup.tsx
  src/components/PostViewer/components/NonAuthModal.tsx
  src/components/PostViewer/components/PostContents.tsx
  src/components/PostViewer/components/PostTitle.tsx
  src/components/PostViewer/components/index.ts
  src/components/PostViewer/constants/index.ts
  src/components/PostViewer/hooks/index.ts
  src/components/PostViewer/hooks/useActionInfo.ts
  src/components/PostViewer/hooks/useContentClassName.ts
  src/components/PostViewer/hooks/useControlRouteByPost.ts
  src/components/PostViewer/hooks/useElementWidth.ts
  src/components/PostViewer/hooks/usePostLike.ts
  src/components/PostViewer/index.tsx
  src/components/PostViewer/style/index.ts
  src/constants/index.ts
Labels: 세진

#127 [Common+Component] - 스크롤 관련 기능 및 컴포넌트, 스타일 추가
  src/components/Icon/index.tsx
  src/components/Main/ToTopButton.tsx
  src/components/Main/index.tsx
  src/hooks/useScrollToTop.ts
  src/styles/commonStyles.css
Labels: 세진

#130 [Refactor & Style] - MyPage 중간 Merge
  src/apis/user.ts
  src/components/Button/index.tsx
  src/components/Image/index.tsx
  src/pages/MyPage/MyInfo.tsx
  src/pages/MyPage/constants/index.ts
  src/pages/MyPage/hooks/index.ts
  src/pages/MyPage/hooks/useLogOut.ts
  src/pages/MyPage/hooks/useUpdateFullName.ts
  src/pages/MyPage/hooks/useUpdatePassWord.ts
  src/pages/MyPage/hooks/useUpdateProfile.ts
  src/pages/MyPage/index.tsx
  src/pages/UserPage/index.tsx
  src/utils/userAuthentication.ts
Labels: 지윤

#133 [Page] - 404 페이지 구현
  src/pages/NotFoundPage/index.tsx
  src/pages/index.ts
  src/routes/index.ts
Labels: 영준

#135 [Feat] - 홈페이지에서 투표한 컨텐츠 보이게 수정
  src/components/PostViewer/components/PostContents.tsx
  src/components/PostViewer/hooks/useContentClassName.ts
  src/components/PostViewer/index.tsx
  src/pages/HomePage/index.tsx
Labels: 세진

#136 [Notification] - 알림 조회 및 읽음 처리 기능 구현
  src/apis/notifications.ts
  src/apis/post.ts
  src/components/Icon/index.tsx
  src/components/NavBar/MenuBar/AuthMenuBar.tsx
  src/components/NavBar/index.tsx
  src/components/NotificationViewer/CommentNotificationItem/index.tsx
  src/components/NotificationViewer/FollowNotificationItem/index.tsx
  src/components/NotificationViewer/LikeNotificationItem/index.tsx
  src/components/NotificationViewer/index.tsx
  src/styles/commonStyles.ts
  src/types/index.ts
Labels: 민우

#139 [Refactor] - 검색 페이지 리팩토링 작업
  src/apis/search.ts
  src/apis/user.ts
  src/components/Header/hooks/useSelect.ts
  src/components/Header/index.tsx
  src/components/PostList/index.tsx
  src/components/PostList/utils/index.ts
  src/components/PostListItem/constants/index.ts
  src/components/PostListItem/hooks/useDeletePost.ts
  src/components/PostListItem/index.tsx
  src/components/UserList/index.tsx
  src/components/UserListItem/index.tsx
  src/constants/index.ts
  src/pages/MyPage/index.tsx
  src/pages/SearchPage/hooks/usePostSort.ts
  src/pages/SearchPage/hooks/useUserSort.ts
  src/pages/SearchPage/index.tsx
  src/pages/SearchPage/utils/index.ts
Labels: 영준

#143 [Createpost & SearchBar] - CreatePost, SearchBar 기능 수정 및 반응형 css 구현
  public/images/LOGO_SMALL.svg
  src/components/LinkButton/index.tsx
  src/components/NavBar/MenuBar/CommonMenuBar.tsx
  src/components/SearchBar/index.tsx
  src/pages/CreatePostPage/index.tsx
Labels: 민우

#144 [Refactor] - PostPage 리펙토링 작업
  src/pages/PostPage/CommentList.tsx
  src/pages/PostPage/Hooks/index.ts
  src/pages/PostPage/Hooks/useCheckVoted.ts
  src/pages/PostPage/Hooks/useCommentNotification.ts
  src/pages/PostPage/Hooks/useControlRouteByComment.ts
  src/pages/PostPage/Hooks/useCreateComment.ts
  src/pages/PostPage/Hooks/useDeleteComment.ts
  src/pages/PostPage/Hooks/useGetDeleteCommentState.ts
  src/pages/PostPage/Hooks/useSelectItem.ts
  src/pages/PostPage/Hooks/useVotingResult.ts
  src/pages/PostPage/MakeComment.tsx
  src/pages/PostPage/components/CommentDeletionFailModal.tsx
  src/pages/PostPage/components/CommentDeletionModal.tsx
  src/pages/PostPage/components/CommentItem.tsx
  src/pages/PostPage/components/CommentList.tsx
  src/pages/PostPage/components/MakeComment.tsx
  src/pages/PostPage/components/Turnout.tsx
  src/pages/PostPage/components/index.ts
  src/pages/PostPage/constants/index.ts
  src/pages/PostPage/index.tsx
  src/utils/voteRatio.ts
Labels: 주하

#146 [Refactor] - LoginPage 리펙토링 작업
  src/pages/LoginPage/constants/index.ts
  src/pages/LoginPage/hooks/index.ts
  src/pages/LoginPage/hooks/useLogin.ts
  src/pages/LoginPage/index.tsx
  src/pages/LoginPage/utils/index.ts
Labels: 주하

#148 [Feat] - 레벨업 감지 기능 및 축하 컴포넌트 추가
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/apis/comment.ts
  src/apis/level.ts
  src/apis/post.ts
  src/apis/profile.ts
  src/components/Icon/index.tsx
  src/components/LevelViewer/components/LevelModal.tsx
  src/components/LevelViewer/hooks/useConfetti.tsx
  src/components/LevelViewer/index.tsx
  src/components/LevelViewer/utils/checkIsNumber.ts
  src/components/Main/index.tsx
  src/hooks/useArchives.ts
  src/store/level.ts
  src/types/auth.ts
  src/types/level.ts
  src/utils/calculateUserLevel.ts
Labels: 세진

#149 [Feat & Refactor] MyPage 반응형 및 리팩토링
  src/constants/index.ts
  src/pages/MyPage/MyInfo.tsx
  src/pages/MyPage/constants/index.ts
  src/pages/MyPage/hooks/useLogOut.ts
  src/pages/MyPage/hooks/useUpdateFullName.ts
  src/pages/MyPage/hooks/useUpdatePassWord.ts
  src/pages/MyPage/hooks/useUpdateProfile.ts
Labels: 지윤

#150 [Refactor] - Home 페이지 리팩토링 작업
  src/pages/HomePage/constants/index.ts
  src/pages/HomePage/hooks/useInfiniteScroll.ts
  src/pages/HomePage/index.tsx
Labels: 영준

#152 [Refactor] - PostPage 리펙토링 작업
  src/pages/PostPage/components/MakeComment.tsx
  src/pages/PostPage/index.tsx
Labels: 주하

#154 [Refactor] - UserPage 유저 변경 시 렌더링 수정
  src/pages/UserPage/index.tsx
Labels: 지윤

#167 [Fix] - 404 페이지 버그 수정
  src/hooks/useCurrentPage.ts
  src/routes/index.ts
  vercel.json
Labels: 영준

#168 [Refactor] - 검색 페이지 hooks 경로 수정
  src/components/PostList/index.tsx
  src/components/PostListItem/hooks/index.ts
  src/components/PostListItem/index.tsx
  src/components/UserList/index.tsx
  src/pages/SearchPage/hooks/index.ts
Labels: 영준

#169 [Refactor] - Header 컴포넌트 hooks 경로 수정
  src/components/Header/components/TabBarList.tsx
  src/components/Header/components/index.ts
  src/components/Header/hooks/index.ts
  src/components/Header/index.tsx
Labels: 영준

#170 [Refactor] - Home 페이지 hooks 경로 수정
  src/pages/HomePage/hooks/index.ts
  src/pages/HomePage/index.tsx
Labels: 영준

#158 [Fix] - 유저, 마이 페이지 포스트 리스트에 프로필 이미지 안 뜨는 현상 수정
  src/pages/MyPage/index.tsx
  src/pages/UserPage/index.tsx
Labels: 지윤

#162 [Fix] - MyPage 닉네임 변경 버그 수정
  src/pages/MyPage/hooks/useUpdateFullName.ts
  src/utils/userAuthentication.ts
Labels: 지윤

#160 [Refactor] - CreatePost 페이지 리팩토링
  src/pages/CreatePostPage/constants/index.ts
  src/pages/CreatePostPage/hooks/index.ts
  src/pages/CreatePostPage/hooks/useCreatePost.ts
  src/pages/CreatePostPage/index.tsx
Labels: 민우

#164 [Style] - LoginPage 반응형 스타일 추가
  src/pages/LoginPage/index.tsx
Labels: 주하

#163 [Refactor] - SignUpPage 리펙토링 작업
  src/pages/LoginPage/constants/index.ts
  src/pages/LoginPage/index.tsx
  src/pages/PostPage/index.tsx
  src/pages/SignUpPage/components/InputEmail.tsx
  src/pages/SignUpPage/components/InputFullName.tsx
  src/pages/SignUpPage/components/InputPassword.tsx
  src/pages/SignUpPage/components/InputPasswordConfirm.tsx
  src/pages/SignUpPage/components/Modals.tsx
  src/pages/SignUpPage/components/index.ts
  src/pages/SignUpPage/constants/index.ts
  src/pages/SignUpPage/hooks/index.ts
  src/pages/SignUpPage/hooks/useAllValidationPass.ts
  src/pages/SignUpPage/hooks/useClickEye.ts
  src/pages/SignUpPage/hooks/useEmailCheck.ts
  src/pages/SignUpPage/hooks/useFullNameCheck.ts
  src/pages/SignUpPage/hooks/usePasswordCheck.ts
  src/pages/SignUpPage/hooks/useSubmit.ts
  src/pages/SignUpPage/index.tsx
  src/utils/userAuthentication.ts
Labels: 주하

#166 [Refactor] - NotificationViewer 컴포넌트 리팩토링
  src/components/NotificationViewer/components/CommentNotificationItem.tsx
  src/components/NotificationViewer/components/DecideNotificationType.tsx
  src/components/NotificationViewer/components/FollowNotificationItem.tsx
  src/components/NotificationViewer/components/LikeNotificationItem.tsx
  src/components/NotificationViewer/components/index.ts
  src/components/NotificationViewer/constants/index.ts
  src/components/NotificationViewer/hooks/useNotification.ts
  src/components/NotificationViewer/index.tsx
  src/components/NotificationViewer/utils/index.ts
Labels: 민우

#156 [Refactor] - SearchBar 컴포넌트 리팩토링
  src/components/SearchBar/constants/index.ts
  src/components/SearchBar/hooks/index.ts
  src/components/SearchBar/hooks/useKeyword.ts
  src/components/SearchBar/index.tsx
Labels: 민우

#176 [Fix] - UserPage 1차 QA 사항 수정
  src/pages/UserPage/hooks/useFollow.ts
Labels: 지윤

#174 [Fix] - NotificationViewer 1차 QA 결과 반영
  src/components/NotificationViewer/components/CommentNotificationItem.tsx
  src/components/NotificationViewer/components/FollowNotificationItem.tsx
  src/components/NotificationViewer/components/LikeNotificationItem.tsx
Labels: 민우

#179 [Fix] - MyPage 1차 QA 결과 반영
  src/apis/user.ts
  src/pages/MyPage/MyInfo.tsx
  src/pages/MyPage/constants/index.ts
  src/pages/MyPage/hooks/useUpdateFullName.ts
  src/pages/MyPage/hooks/useUpdatePassWord.ts
  src/pages/MyPage/index.tsx
  src/pages/UserPage/UserInfo.tsx
  src/utils/userAuthentication.ts
Labels: 지윤

#180 [Fix] - PostPage 1차 QA 결과 반영
  package-lock.json
  src/pages/PostPage/components/CommentDeletionModal.tsx
  src/pages/PostPage/components/CommentList.tsx
  src/pages/PostPage/components/MakeComment.tsx
  src/pages/PostPage/constants/index.ts
  src/pages/PostPage/index.tsx
Labels: 주하

#184 [Fix] - LoginPage 1차 QA 결과 반영
  src/pages/LoginPage/index.tsx
Labels: 주하

#188 [Fix] - Header 컴포넌트 1차 QA 결과 반영
  src/components/Header/components/TabBarList.tsx
  src/components/Header/index.tsx
Labels: 영준

#191 [Fix] - level 기능 1차 QA 결과 반영
  src/apis/auth.ts
Labels: 세진

#192 [Fix] - PostViewer 컴포넌트 1차 QA 결과 반영
  src/components/PostViewer/components/ButtonGroup.tsx
  src/components/PostViewer/components/PostContents.tsx
  src/components/PostViewer/components/PostTitle.tsx
  src/components/PostViewer/constants/index.ts
  src/components/PostViewer/hooks/useControlRouteByPost.ts
  src/components/PostViewer/index.tsx
Labels: 세진

#194 [Feat] - 로그인 안되어있을 시 redirect 기능하는 hook
  src/apis/comment.ts
  src/apis/post.ts
  src/components/Main/index.tsx
  src/components/NavBar/MenuBar/CommonMenuBar.tsx
  src/hooks/index.ts
  src/hooks/useCurrentPage.ts
  src/hooks/useRedirectByAuth.ts
  src/pages/MyPage/index.tsx
Labels: 세진

#186 [Fix] - CreatePost 페이지 1차 QA 결과 반영
  src/pages/CreatePostPage/constants/index.ts
  src/pages/CreatePostPage/hooks/useCreatePost.ts
  src/pages/CreatePostPage/index.tsx
Labels: 민우

#195 [Refactor] - mypage, userpage 이미지 삭제
  src/pages/MyPage/index.tsx
  src/pages/UserPage/index.tsx
Labels: 지윤

#198 [Feat] - auth 리다이렉트 route 에서 관리하는 기능 추가
  src/apis/level.ts
  src/components/Main/index.tsx
  src/routes/index.ts
Labels: 세진

#204 [Fix] - 모달 createPortal로 변경
  src/components/Modal/components/ModalViewer.tsx
  src/components/Modal/index.tsx
Labels: 지윤

#208 [Fix] - PostPage 뒤로가기 처리 및 최적화
  package-lock.json
  src/pages/PostPage/Hooks/useCheckVoted.ts
  src/pages/PostPage/Hooks/useCommentNotification.ts
  src/pages/PostPage/Hooks/useControlRouteByComment.ts
  src/pages/PostPage/Hooks/useCreateComment.ts
  src/pages/PostPage/Hooks/useDeleteComment.ts
  src/pages/PostPage/Hooks/useGetDeleteCommentState.ts
  src/pages/PostPage/index.tsx
Labels: 주하

#205 [Fix] - 공통 코드 이슈 수정
  src/App.tsx
  src/apis/auth.ts
  src/apis/notifications.ts
  src/apis/post.ts
  src/components/Header/hooks/useSelect.ts
  src/components/Header/index.tsx
  src/components/LevelViewer/components/LevelModal.tsx
  src/components/Main/ToTopButton.tsx
  src/components/Main/index.tsx
  src/components/Modal/index.tsx
  src/components/NavBar/MenuBar/index.ts
  src/components/NavBar/components/AuthMenuBar.tsx
  src/components/NavBar/components/CommonMenuBar.tsx
  src/components/NavBar/components/NonAuthMenuBar.tsx
  src/components/NavBar/components/index.ts
  src/components/NavBar/index.tsx
  src/components/NotificationViewer/components/CommentNotificationItem.tsx
  src/components/NotificationViewer/components/DecideNotificationType.tsx
  src/components/NotificationViewer/components/FollowNotificationItem.tsx
  src/components/NotificationViewer/components/LikeNotificationItem.tsx
  src/components/NotificationViewer/index.tsx
  src/components/NotificationViewer/utils/index.ts
  src/components/PostList/index.tsx
  src/components/PostListItem/index.tsx
  src/components/PostViewer/components/ButtonGroup.tsx
  src/components/PostViewer/components/NonAuthModal.tsx
  src/components/PostViewer/components/PostTitle.tsx
  src/components/PostViewer/hooks/useControlRouteByPost.ts
  src/components/SearchBar/hooks/useKeyword.ts
  src/components/SearchBar/index.tsx
  src/components/UserList/index.tsx
  src/components/UserListItem/index.tsx
  src/components/index.ts
  src/pages/CreatePostPage/index.tsx
  src/pages/HomePage/hooks/useInfiniteScroll.ts
  src/pages/HomePage/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/MyPage/components/MyInfo.tsx
  src/pages/MyPage/hooks/useUpdateFullName.ts
  src/pages/MyPage/hooks/useUpdatePassWord.ts
  src/pages/MyPage/index.tsx
  src/pages/PostPage/Hooks/useGetDeleteCommentState.ts
  src/pages/PostPage/components/CommentDeletionFailModal.tsx
  src/pages/PostPage/components/CommentDeletionModal.tsx
  src/pages/PostPage/components/CommentItem.tsx
  src/pages/PostPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SignUpPage/components/InputEmail.tsx
  src/pages/SignUpPage/components/InputFullName.tsx
  src/pages/SignUpPage/components/InputPassword.tsx
  src/pages/SignUpPage/components/InputPasswordConfirm.tsx
  src/pages/SignUpPage/components/Modals.tsx
  src/pages/SignUpPage/index.tsx
  src/pages/UserPage/components/UserInfo.tsx
  src/pages/UserPage/index.tsx
  src/styles/icons/SearchIcon.tsx
  src/utils/calculateUserLevel.ts
  src/utils/pxToRem.ts
Labels: 세진

#209 [Fix] - z-index 상수화
  src/components/LevelViewer/components/LevelModal.tsx
  src/components/NotificationViewer/index.tsx
  src/components/PostViewer/components/PostTitle.tsx
  src/pages/PostPage/components/MakeComment.tsx
  src/pages/PostPage/components/Turnout.tsx
  src/styles/commonStyles.ts
Labels: 세진

#211 [Style] - 반응형 수정 및 추가
  index.html
  src/App.tsx
  src/components/Button/index.tsx
  src/components/Header/index.tsx
  src/components/Icon/index.tsx
  src/components/LinkButton/index.tsx
  src/components/Main/index.tsx
  src/components/NavBar/components/CommonMenuBar.tsx
  src/components/NavBar/components/DropDownAuthMenu.tsx
  src/components/NavBar/components/DropDownNonAuthMenu.tsx
  src/components/NavBar/components/index.ts
  src/components/NavBar/index.tsx
  src/components/NotificationViewer/index.tsx
  src/components/PostListItem/index.tsx
  src/components/PostViewer/components/PostTitle.tsx
  src/components/SearchBar/index.tsx
  src/components/UserListItem/index.tsx
  src/hooks/index.ts
  src/hooks/useWindowWidth.ts
  src/pages/CreatePostPage/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/PostPage/components/CommentItem.tsx
  src/pages/PostPage/components/MakeComment.tsx
  src/pages/PostPage/index.tsx
  src/styles/commonStyles.css
  src/styles/commonStyles.ts
Labels: 세진

#216 [Feat] - meta 태그 추가
  index.html
Labels: 영준

#217 [Feat] - og image 크기 설정
  index.html
Labels: 영준

#218 [Feat] - og image 경로 수정
  index.html
Labels: 영준

#219 [Feat] - og type 설정 및 이미지 경로 변경
  index.html
Labels: 영준
